const page=document.body.dataset.page;
const navStyles=document.createElement('link');navStyles.rel='stylesheet';navStyles.href='checkmark-nav-update.css';document.head.appendChild(navStyles);
const brandStyles=document.createElement('link');brandStyles.rel='stylesheet';brandStyles.href='checkmark-header-brand.css?v=20261007-wordmark-center';document.head.appendChild(brandStyles);
const titlePanelStyles=document.createElement('link');titlePanelStyles.rel='stylesheet';titlePanelStyles.href='checkmark-title-panels.css?v=20260905-2';document.head.appendChild(titlePanelStyles);
const bevelStyles=document.createElement('link');bevelStyles.rel='stylesheet';bevelStyles.href='checkmark-bevels.css?v=20260925-wash3';document.head.appendChild(bevelStyles);
const responsiveStyles=document.createElement('link');responsiveStyles.rel='stylesheet';responsiveStyles.href='checkmark-responsive.css?v=20260922-1';document.head.appendChild(responsiveStyles);
const links={home:'index.html',services:'services.html',recording:'recording.html',mixing:'mixing-mastering.html',live:'live-recordings.html',studioA:'studio-a.html',studioB:'studio-b.html',artists:'featured-artists.html',team:'team.html',community:'community.html',faq:'faq.html'};
const current=name=>page===name?' aria-current="page"':'';
const serviceSectionCurrent=['services','recording','mixing','live'].includes(page)?' aria-current="page"':'';
document.getElementById('site-header').innerHTML=`<header class="header"><nav class="wrap"><a class="logo" href="${links.home}" aria-label="Checkmark Audio home"><img src="MEDIA/IMAGES/checkmark-audio-logo-official-gold-gradient-transparent.png" alt="" width="2000" height="2000"><span>Checkmark Audio</span></a><div class="navlinks" id="navlinks"><a${current('home')} href="${links.home}">Home</a><a${serviceSectionCurrent} href="${links.services}">Services</a><a${current('studioA')} href="${links.studioA}">Studio A</a><a${current('studioB')} href="${links.studioB}">Studio B</a><a${current('artists')} href="${links.artists}">Artists</a><a${current('team')} href="${links.team}">Team</a><a${current('community')} href="${links.community}">Live</a><a${current('faq')} href="${links.faq}">Q &amp; A</a></div><button class="menu" type="button" aria-expanded="false" aria-controls="navlinks">Menu</button><a class="btn primary header-cta" href="${links.home}#book"><span class="header-cta-spark" aria-hidden="true">✦</span>Book a free consultation</a></nav></header>`;
document.getElementById('site-footer').innerHTML=`<footer class="footer"><div class="wrap footgrid"><div><img src="MEDIA/IMAGES/checkmark-audio-logo-official-gold-gradient-transparent.png" alt="" width="58" height="58"><p>Recording, mixing, mastering, and live recordings in Albuquerque, New Mexico.</p><p>5413 Lomas Blvd NE, Albuquerque, NM 87110 · <a href="tel:+15052670558">505-267-0558</a></p></div><div><b class="condensed">Explore</b><ul><li><a href="${links.services}">All Services &amp; Pricing</a></li><li><a href="${links.artists}">Featured Artists</a></li><li><a href="${links.recording}">Recording</a></li><li><a href="${links.mixing}">Mixing &amp; Mastering</a></li><li><a href="${links.live}">Checkmark Live</a></li></ul></div><div><b class="condensed">Studio</b><ul><li><a href="${links.studioA}">Studio A</a></li><li><a href="${links.studioB}">Studio B</a></li><li><a href="${links.community}">Live</a></li><li><a href="${links.faq}">Q &amp; A</a></li></ul></div></div></footer>`;
const navigationBehavior=document.createElement('script');navigationBehavior.src='checkmark-navigation.js?v=20260922-2';document.body.appendChild(navigationBehavior);
if(['recording','mixing','live'].includes(page)){
  const bookingStyles=document.createElement('link');bookingStyles.rel='stylesheet';bookingStyles.href='checkmark-service-booking.css';document.head.appendChild(bookingStyles);
  const liveCalendarStyles=document.createElement('link');liveCalendarStyles.rel='stylesheet';liveCalendarStyles.href='checkmark-live-calendar.css';document.head.appendChild(liveCalendarStyles);
  const serviceNames={recording:'Recording',mixing:'Mixing & Mastering',live:'Checkmark Live'},serviceTopics={recording:'recording',mixing:'mixing & mastering',live:'Checkmark Live'},servicePrices={recording:'Vocal recording from $50/hour · band recording from $75/hour · other studio/engineering from $65/hour',mixing:'Studio and engineering work from $65/hour · larger projects quoted',live:'Project-based custom quote'};
  const calendar=document.createElement('section');calendar.className='service-calendar';calendar.innerHTML=`<div class="wrap"><div class="service-calendar-head"><div><p class="eyebrow">Book a consultation</p><h2>Select a time to discuss ${serviceTopics[page]}.</h2></div><p>Choose an available time below to book a free one-hour consultation. Prefer to send project details first? The inquiry form is always open.</p></div><div class="calendar-frame"><aside class="calendar-info"><p class="eyebrow">${serviceNames[page]}</p><h3>Free consultation · 1 hour</h3><p>${servicePrices[page]}</p><p>Talk through your project and next steps. A consultation can include a studio tour and pricing guidance.</p><div class="calendar-actions"><a class="btn primary" href="${links.home}#book">Prefer an inquiry?</a><a class="btn" href="tel:+15052670558">Call the studio</a></div></aside><div class="calendar-schedule live-calendar" aria-label="Book a free Checkmark Audio consultation"><div class="cal-live-frame" id="cal-inline" title="Book a free Checkmark Audio consultation"></div></div></div></div>`;document.querySelector('.pagecta').after(calendar);
  // Same Cal.com embed + booking emails as the home page (ordered, non-async loads).
  const bookingScripts=[];
  if(!window.emailjs)bookingScripts.push('https://cdn.jsdelivr.net/npm/@emailjs/browser@4/dist/email.min.js');
  if(typeof EMAILJS_SERVICE==='undefined')bookingScripts.push('checkmark-emailjs.js?v=20261008-cal-embed');
  bookingScripts.push('checkmark-cal-booking.js?v=20261008-cal-embed');
  for(const src of bookingScripts){const script=document.createElement('script');script.src=src;script.async=false;document.body.appendChild(script)}
}
const goldThemeStyles=document.createElement('link');goldThemeStyles.rel='stylesheet';goldThemeStyles.href='checkmark-gold-theme.css?v=20260925-bebas2';document.head.appendChild(goldThemeStyles);
const panelTextureStyles=document.createElement("link");panelTextureStyles.rel="stylesheet";panelTextureStyles.href="checkmark-panel-texture.css?v=20260925-goldpaper-banners";document.head.appendChild(panelTextureStyles);

const mediaLoader=document.createElement('script');mediaLoader.src='checkmark-media-loader.js?v=20260827-1';document.body.appendChild(mediaLoader);
if(['localhost','127.0.0.1','0.0.0.0'].includes(location.hostname)){const editorStyles=document.createElement('link');editorStyles.rel='stylesheet';editorStyles.href='checkmark-site-media-editor.css?v=20260827-1';document.head.appendChild(editorStyles);mediaLoader.addEventListener('load',()=>{const editor=document.createElement('script');editor.src='checkmark-site-media-editor.js?v=20260922-2';document.body.appendChild(editor)})}

const roundedBevelStyles=document.createElement("link");roundedBevelStyles.rel="stylesheet";roundedBevelStyles.href="checkmark-rounded-bevels.css?v=20260925-wash3";document.head.appendChild(roundedBevelStyles);
