const page=document.body.dataset.page;
const navStyles=document.createElement('link');navStyles.rel='stylesheet';navStyles.href='checkmark-nav-update.css';document.head.appendChild(navStyles);
const brandStyles=document.createElement('link');brandStyles.rel='stylesheet';brandStyles.href='checkmark-header-brand.css?v=2';document.head.appendChild(brandStyles);
const links={home:'index.html',services:'services.html',recording:'recording.html',mixing:'mixing-mastering.html',live:'live-recordings.html',studioA:'studio-a.html',studioB:'studio-b.html',team:'team.html',community:'community.html'};
const current=name=>page===name?' aria-current="page"':'';
document.getElementById('site-header').innerHTML=`<header class="header"><nav class="wrap"><a class="logo" href="${links.home}" aria-label="Checkmark Audio home"><img src="MEDIA/IMAGES/checkmark-audio-logo-official-gold-gradient-transparent.png" alt="" width="2000" height="2000"><span>Checkmark Audio</span></a><div class="navlinks" id="navlinks"><a${current('home')} href="${links.home}">Home</a><div class="navdrop"><a${current('services')} class="services-link" href="${links.services}">Services</a><button type="button" aria-expanded="false" aria-label="Open services menu"><span aria-hidden="true">⌄</span></button><div class="navdrop-menu"><a${current('recording')} href="${links.recording}">Recording</a><a${current('mixing')} href="${links.mixing}">Mixing &amp; Mastering</a><a${current('live')} href="${links.live}">Live Recordings</a></div></div><a${current('studioA')} href="${links.studioA}">Studio A</a><a${current('studioB')} href="${links.studioB}">Studio B</a><a${current('team')} href="${links.team}">Team</a><a${current('community')} href="${links.community}">Community</a></div><button class="menu" type="button" aria-expanded="false" aria-controls="navlinks">Menu</button><a class="btn primary" href="${links.home}#book">Free consultation</a></nav></header>`;
document.getElementById('site-footer').innerHTML=`<footer class="footer"><div class="wrap footgrid"><div><img src="MEDIA/IMAGES/checkmark-audio-logo-official-gold-gradient-transparent.png" alt="" width="58" height="58"><p>Recording, mixing, mastering, and live recordings in Albuquerque, New Mexico.</p><p>Website preview · content pending final approval.</p></div><div><b class="condensed">Explore</b><ul><li><a href="${links.services}">All Services &amp; Pricing</a></li><li><a href="${links.recording}">Recording</a></li><li><a href="${links.mixing}">Mixing &amp; Mastering</a></li><li><a href="${links.live}">Live Recordings</a></li></ul></div><div><b class="condensed">Studio</b><ul><li><a href="${links.studioA}">Studio A</a></li><li><a href="${links.studioB}">Studio B</a></li><li><a href="${links.community}">Community</a></li></ul></div></div></footer>`;
const menu=document.querySelector('.menu'),nav=document.getElementById('navlinks'),drop=document.querySelector('.navdrop'),dropButton=drop.querySelector('button');menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',open)});dropButton.addEventListener('click',()=>{const open=drop.classList.toggle('open');dropButton.setAttribute('aria-expanded',open)});
const stickyHeader=document.querySelector('.header');
function setStickyHeaderState(){stickyHeader.classList.toggle('is-scrolled',scrollY>18)}
addEventListener('scroll',setStickyHeaderState,{passive:true});
setStickyHeaderState();
if(page==='studioA'||page==='studioB'){
  const galleryStyles=document.createElement('link');galleryStyles.rel='stylesheet';galleryStyles.href='checkmark-gallery.css';document.head.appendChild(galleryStyles);
  const studioA=[['control-room-desk-view-03.webp','Studio A control-room workstation','Control room'],['studio-waiting-area-red-wall.webp','Studio A waiting area','Waiting area'],['studio-a-guitar-mural-hallway.webp','Guitar mural hallway in Studio A','Studio character'],['vocal-recording-albuquerque-nm-control-room-microphone.webp','Microphone and control-room view in Studio A','Vocal capture'],['music-production-collaborative-session-checkmark-audio.webp','Collaborative production session at Checkmark Audio','Collaboration'],['studio-patch-bay-and-rack-gear-view-03.webp','Studio A patch bay and rack equipment','Signal chain'],['synth-keyboards-view-03.webp','Stacked synthesizer keyboards in Studio A','Instruments'],['checkmark-audio-on-air-interview-behind-the-scenes-view-09.webp','Behind the scenes of an interview session in Studio A','Behind the scenes'],['mixing-console-close-up-view-02.webp','Studio A mixing console detail','Mixing detail'],['acoustic-guitar-hands-close-up-recording-session.webp','Acoustic guitar recording session','Instrument recording'],['checkmark-audio-lounge-sign.webp','Checkmark Audio lounge sign','Lounge'],['recording-studio-albuquerque-nm-checkmark-sign.webp','Checkmark Audio recording-studio sign','Studio identity']];
  const studioB=[['studio-b-instrument-room-view-01.webp','Studio B instrument and recording room','Recording room'],['studio-b-control-room-desk-synth-view-01.webp','Studio B workstation and synthesizer','Workstation'],['studio-b-vocal-booth-window-recording-engineer-checkmark-audio-view-03.webp','Engineer looking into the Studio B vocal booth','Booth connection'],['vocal-recording-artist-booth-purple-light.webp','Artist recording in the Studio B vocal booth','Artist session'],['studio-b-drum-recording-setup.webp','Drum recording setup in Studio B','Drum setup'],['vocal-booth-microphone-warm-light.webp','Studio B vocal-booth microphone under warm light','Warm-light booth'],['studio-b-instrument-room-black-and-white.webp','Black-and-white view of the Studio B instrument room','Acoustic room'],['vocal-recording-artist-booth-rear.webp','Artist recording from behind in the Studio B booth','Vocal performance'],['drum-recording-cymbal-detail.webp','Cymbal detail during a Studio B recording setup','Session detail'],['vocalist-through-studio-window-view-02.webp','Vocalist seen through the Studio B window','Through the glass'],['vocal-booth-microphone-blue-green-light.webp','Studio B microphone under blue-green booth lighting','Booth atmosphere'],['checkmark-audio-vocal-recording-booth-view-02.webp','Checkmark Audio Studio B vocal booth','Vocal booth']];
  const selected=page==='studioA'?studioA:studioB,folder=page==='studioA'?'studio-a':'studio-b',title=page==='studioA'?'Rooms, sessions, and details.':'Focused, intimate, flexible.',intro=page==='studioA'?'A varied exploratory gallery from the approved Studio A media assignment: control room, lobby, performance space, vocal capture, instruments, gear, and working sessions.':'A varied exploratory gallery from the approved Studio B media assignment: booth, shared workspace, acoustic instruments, performers, microphones, drums, and changing room light.';
  const gallery=document.createElement('section');gallery.className='gallery-section';gallery.innerHTML=`<div class="wrap"><div class="gallery-head"><div><p class="eyebrow">Inside ${page==='studioA'?'Studio A':'Studio B'}</p><h2>${title}</h2></div><p>${intro}</p></div><div class="photo-gallery">${selected.map(([file,alt,caption])=>`<figure><img loading="lazy" src="MEDIA/IMAGES/BY_PAGE/${folder}/${file}" alt="${alt}"><figcaption>${caption}</figcaption></figure>`).join('')}</div></div>`;document.querySelector('.pagecta').before(gallery);
}
if(['recording','mixing','live'].includes(page)){
  const bookingStyles=document.createElement('link');bookingStyles.rel='stylesheet';bookingStyles.href='checkmark-service-booking.css';document.head.appendChild(bookingStyles);
  const liveCalendarStyles=document.createElement('link');liveCalendarStyles.rel='stylesheet';liveCalendarStyles.href='checkmark-live-calendar.css';document.head.appendChild(liveCalendarStyles);
  const serviceNames={recording:'Recording',mixing:'Mixing & Mastering',live:'Live Recordings'},servicePrices={recording:'Vocal recording from $50/hour · band recording from $75/hour · other studio/engineering from $65/hour',mixing:'Studio and engineering work from $65/hour · larger projects quoted',live:'Project-based custom quote'};
  const calendar=document.createElement('section');calendar.className='service-calendar';calendar.innerHTML=`<div class="wrap"><div class="service-calendar-head"><div><p class="eyebrow">Book a consultation</p><h2>Select a time to discuss ${serviceNames[page].toLowerCase()}.</h2></div><p>This is Checkmark Audio’s live, directly bookable calendar for a free one-hour consultation. Choose an available time below; the inquiry form remains available if you would rather send project details first.</p></div><div class="calendar-frame"><aside class="calendar-info"><p class="eyebrow">${serviceNames[page]}</p><h3>Free consultation · 1 hour</h3><p>${servicePrices[page]}</p><p>The consultation is for discussing your project and next steps. Paid studio-session scheduling is a separate future workflow.</p><div class="calendar-actions"><a class="btn primary" href="${links.home}#book">Prefer an inquiry?</a><a class="btn" href="tel:+15052670558">Call the studio</a></div></aside><div class="calendar-schedule live-calendar" aria-label="Book a free Checkmark Audio consultation"><iframe class="cal-live-frame" title="Book a free Checkmark Audio consultation" src="https://cal.com/checkmarkaudio/consult?embed=1&layout=month_view&theme=light" loading="lazy"></iframe></div></div></div>`;document.querySelector('.pagecta').after(calendar);
}
